"""currenct is notnull

Revision ID: 166ca87ba6cb
Revises: 7fb69cb32431
Create Date: 2022-11-29 20:14:22.319580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166ca87ba6cb'
down_revision = '7fb69cb32431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
