"""User email and phone validate added

Revision ID: 317921084ef5
Revises: e130326a063f
Create Date: 2022-11-07 15:00:10.953301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317921084ef5'
down_revision = 'e130326a063f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('phone_activated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('email_activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_activated')
    op.drop_column('users', 'email_code')
    op.drop_column('users', 'phone_activated')
    op.drop_column('users', 'phone_code')
    # ### end Alembic commands ###
