"""added image url to product and category

Revision ID: 34ae2af4e323
Revises: 57db8b44bd1d
Create Date: 2022-11-29 20:04:40.548132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ae2af4e323'
down_revision = '57db8b44bd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_count')
    # ### end Alembic commands ###
