"""Added CartItems model

Revision ID: 450f218d7eab
Revises: cf32a56ab9fb
Create Date: 2022-11-27 21:29:10.819644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450f218d7eab'
down_revision = 'cf32a56ab9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    # ### end Alembic commands ###
