"""added image url to product and category

Revision ID: 57db8b44bd1d
Revises: 03ea23b3e865
Create Date: 2022-11-29 14:40:26.191292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57db8b44bd1d'
down_revision = '03ea23b3e865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
