"""added currency to products

Revision ID: 7fb69cb32431
Revises: 98beedf3ddfd
Create Date: 2022-11-29 20:13:36.871377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb69cb32431'
down_revision = '98beedf3ddfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('currency', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'currency')
    # ### end Alembic commands ###
