"""Added Item model

Revision ID: 936ccb8f0080
Revises: 1b4d123cb87e
Create Date: 2022-11-27 21:06:16.048149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936ccb8f0080'
down_revision = '1b4d123cb87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
