"""changed image url to image name and type

Revision ID: 98beedf3ddfd
Revises: 34ae2af4e323
Create Date: 2022-11-29 20:10:59.170121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98beedf3ddfd'
down_revision = '34ae2af4e323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_name', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'image_url')
    op.add_column('products', sa.Column('image_type', sa.Text(), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('products', 'image_type')
    op.add_column('categories', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'image_name')
    # ### end Alembic commands ###
